### ISSUE TITLE
Packages that are missing after splitting out filters

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vsrepo#152]
After removing all bundled filters from the vs core there are a number of packages needed:
https://github.com/vapoursynth/vs-imwri
https://github.com/vapoursynth/vs-eedi3-obsolete (I compiled it and made a release so why not?)

**Comment by theChaosCoder** [comment]
That means they will not be bundled with the VS installer anymore?

**Comment by myrsloik** [comment]
Correct, I'd like to cut down on the required dependencies to compile the core. Also half of them are 100% obsolete anyway.

Of course now we get the problem that vsrepo has no idea about api4 stuff. Will have to fix that soon before it all turns into a huge mess.

**Comment by theChaosCoder** [comment]
I added the first batch of core filters. Idk if putting (obsolete) in the name tag is a good choice...

**Comment by myrsloik** [comment]
They are obsolete. The only reason I didn't straight up delete them completely is that somebody may be need them for lazy script compatibility.

**Comment by myrsloik** [comment]
Added a way to tag required api version so new packages won't be installed in older vs versions and a supported version can be picked.
I think there's still one problem remaining and that's when you start adding script dependencies for the newly split plugins that are bundled with R54. Will have to think of some solution for that as well.

**Comment by myrsloik** [comment]
Proper releases created for everything except imwri now. The last annoying thing to compile on windows...

**Comment by theChaosCoder** [comment]
Why is avisource obsolete?

**Comment by myrsloik** [comment]
Name one case where FFMS2 doesn't work just as well? It's extremely reliable for avi files and rare vfw codecs rarely have x64 versions.

**Comment by theChaosCoder** [comment]
True, but it would be nice if we could have at least a binary. On the german doom9 forum a user asked for help with an old ASF file. Every ffmepg based software/player fails to decode/play it properly. It could help with old legacy crap ^^"

**Comment by myrsloik** [comment]
Sure, I'll shit out a single release then and then let it bitrot.

**Comment by myrsloik** [comment]
Avisource done and tested.

**Comment by myrsloik** [comment]
I think I've solved all coexistence problems for now by blacklisting the bundled plugins when api3 is detected. So it's safe to add them as script dependencies (if any scripts actually use them).

**Comment by theChaosCoder** [comment]
There's already a "vapoursynth-classic" fork xD People really do not like change.

I think the only thing missing for a very smooth transition to v4 are vsrepo scripts, they are old (especially the big ones). Plugins have a relatively good release cycle. Scripts on the other hand have often more changes but far less releases or no releases at all. 

- Last havsfunc release is over a year old but had many important chances since. muvsfunc is even older.
- Some make tagged releases (vsrepo can't handle them, as they are tags and not "real" releases on github)
- Some make no releases at all!

I still think we should just grab the latest commit or maybe introduce a unstable / bleeding edge / latest-shit parameter. As far as I can see, most people just want the latest version. :-/

**Comment by myrsloik** [comment]
I suppose adding a mode for grabbing latest master for scripts could be useful. And switched on for some scripts. I'll see if I have time to add it tomorrow.

**Comment by theChaosCoder** [comment]
I think a similar concept could be also applied to plugins. Sometimes there are pre-released plugins. Implementing it for plugins should be trivial. Instead of skipping pre-releases, we just add them with a pre-release tag.

The only downside I see is that pre-releases could get replaced by a new release (aka deleted). So not really worth implementing I guess.

For scripts we actually have a "seafty net" with the **ignore tag**. We could always exclude a commit (= version) from the updater. This is just in case the latest commit breaks everything and the auhor stops updating for a long time.

p.s.
I already implemented the commit grabbing thingy last year in avsrepo https://github.com/theChaosCoder/avsrepo/blob/8f8999c99d202fde57ecdd00fac4c5317eb6802c/avsupdaterepo.py#L89
https://github.com/theChaosCoder/avsrepo/blob/8f8999c99d202fde57ecdd00fac4c5317eb6802c/avsupdaterepo.py#L227

I had to add a gitbranch tag in case the default branch is not "master".  And path if the script is in a subfolder I think. I don't really remember xD

**Comment by myrsloik** [comment]
I really thought I could spank script writers into making releases. I mean they could do zip drops on doom9 and that's the same thing, right?
What do the package json files look like with this enabled?

**Comment by theChaosCoder** [comment]
Almost the same https://vsdb.top/avspackages.zip
This file has all the "new" stuff https://github.com/theChaosCoder/avsrepo/blob/master/packages/srestore.json

https://github.com/theChaosCoder/avsrepo/tree/master/packages
It still uses the v2 format.

**Comment by myrsloik** [comment]
And there my time ran out for this week. Feel free to implement it in vsrepo using copypasta.

**Comment by theChaosCoder** [comment]
Ok, I'll cook something up.

In my avsrepo implementation I only save the latest commit. Previous commits are not copied. I think this was to avoid an unnecessary long list of versions. That means the commits between 2 update-local calls will not be saved. 

Sounds good?

**Comment by myrsloik** [comment]
Isn't that a bit of a problem? I mean then the installed version will be unknown and updates won't be automatic? At least with the current logic.
If anything I'd have logic along the lines of "grab master form github and insert as a release if more than 2(?) months since the latest release recorded in the package file". That'll give 6 "releases"/year and not clog up too much.
Obviously we can tweak the time but you get the idea. Opinions?

**Comment by theChaosCoder** [comment]
Why would be the installed version unknown? We would have the release hash and the hashes of some! commits inside the package. Everything that was installed via vsrepo will be known.

My logic was: "grab master from github and if latest commit is new -> insert as a release in the package file"

I usually do updates every week or so. This would result in max. 2 releases after a week. 
2 months is a bit long for the "very latest" version.
Often there is a "small burst" of many commits over the weekend in a repo, but we only need the latest one.

But I like the time check idea. That will prevent unnecessary releases if you run vsrupdate.py update-local like every day.

**Comment by myrsloik** [comment]
Ok, I misread it like a consumer side thing. In that case whatever you do plus my time limit idea.

**Comment by theChaosCoder** [comment]
Oh and btw. the commits are checked only for the specific file. If another file in the repo is updated then there it does not count as a new release. This can be filtered by the path parameter of the git commits api.

**Comment by theChaosCoder** [comment]
Almost done.
But idk if I'm too tired or just dumb. I can't get `2021-09-12T17:04:45Z` to parse in python. At least not with the in python included datetime module.

**Comment by myrsloik** [comment]
eedi3 available

**Comment by theChaosCoder** [comment]
It looks like imwri is theoretically ready for a release too?
https://github.com/vapoursynth/vs-imwri/actions/runs/1265873108

**Comment by myrsloik** [comment]
I still haven't tested the binaries. Need to do that first.

**Comment by myrsloik** [comment]
imwri tested and uploaded, this can be closed after it's added

**Comment by theChaosCoder** [comment]
+ imwri added
